-- auth-service schema.
--
-- Portability note: this file, like every migration in the platform, is written
-- in SQL that both PostgreSQL and H2 accept. That is what allows the same
-- migration history to run against PostgreSQL in Docker, against H2 in the
-- `local` profile, and against H2 again in the integration tests, so the schema
-- under test is the schema that ships.
--
-- Consequences of that rule, applied throughout:
--   * UUIDs are generated by the application, not by gen_random_uuid()
--   * no SERIAL / IDENTITY; no jsonb; no ILIKE; no partial indexes
--   * every column type is one both engines spell the same way

CREATE TABLE users (
    id            VARCHAR(36)         NOT NULL,
    first_name    VARCHAR(60)  NOT NULL,
    last_name     VARCHAR(60)  NOT NULL,
    email         VARCHAR(180) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    phone         VARCHAR(20),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Roles are a closed vocabulary owned by this service. A separate table with its
-- own surrogate key would add a join to every sign-in and buy nothing, since
-- roles carry no attributes of their own.
CREATE TABLE user_roles (
    user_id VARCHAR(36)        NOT NULL,
    role    VARCHAR(30) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE addresses (
    id             VARCHAR(36)         NOT NULL,
    user_id        VARCHAR(36)         NOT NULL,
    label          VARCHAR(40)  NOT NULL,
    recipient_name VARCHAR(120) NOT NULL,
    phone          VARCHAR(20)  NOT NULL,
    line1          VARCHAR(200) NOT NULL,
    line2          VARCHAR(200),
    city           VARCHAR(80)  NOT NULL,
    state          VARCHAR(80)  NOT NULL,
    postal_code    VARCHAR(16)  NOT NULL,
    country        VARCHAR(80)  NOT NULL,
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP    NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_addresses_user ON addresses (user_id);

-- A signed JWT cannot be withdrawn, so the refresh token id is tracked here to
-- make sign-out and rotation real. The token string itself is never stored.
CREATE TABLE refresh_tokens (
    id         VARCHAR(36)      NOT NULL,
    user_id    VARCHAR(36)      NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
